apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.29.0 (997957870)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: client
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.29.0 (997957870)
      creationTimestamp: null
      labels:
        io.kompose.network/flower-tutorial-default: "true"
        io.kompose.service: client
    spec:
      containers:
        - env:
            - name: DATA_SPLIT_SERVICE_IP
              value: "fl-orchestrator-service"
            - name: SERVER_IP
              value: "fl-orchestrator-service"
          image: flower_tutorial-client
          name: client
          resources: {}
          imagePullPolicy: Never
        
      restartPolicy: Always
status: {}  
