services:
  client:
    build:
      context: ../../
      dockerfile: ./docker/flower_tutorial/client/Dockerfile
    environment:
      SERVER_IP: "localhost"
    network_mode: "host"
  server:
    container_name: "server"
    build:
      context: ../../
      dockerfile: ./docker/flower_tutorial/server/Dockerfile
    environment:
      SERVER_IP: "localhost"
      NUM_CLIENTS: 3
      NUM_ROUNDS: 15
      NUM_LOCAL_EPOCHS: 5
    network_mode: "host"
  data-split-service:
    container_name: "data-split-service"
    build:
      context: ../../
      dockerfile: ./docker/flower_tutorial/data_split_service/Dockerfile
    environment:
      N_SAMPLES: 10000
      N_SPLITS: 3
      MANUAL_SEED: 1
    network_mode: "host"
