apiVersion: v1
kind: Service
metadata:
  name: fl-orchestrator-service
spec:
  selector:
    # Label selectors to match the Pods with the two containers
    app: fl-orchestrator-service
  ports:
    - name: data-split-service
      port: 8080
      targetPort: 8080
    - name: fl-server
      port: 8081
      targetPort: 8081

